export type Language = {
    name: string;
    code: string;
};

export const SUPPORTED_LANGUAGES: Language[] = [
    { "name": "Afrikaans", "code": "af" },
    { "name": "Afar", "code": "aa" },
    { "name": "Albanian", "code": "sq" },
    { "name": "Amharic", "code": "am" },
    { "name": "Arabic", "code": "ar" },
    { "name": "Armenian", "code": "hy" },
    { "name": "Assamese", "code": "as" },
    { "name": "Aymara", "code": "ay" },
    { "name": "Azerbaijani", "code": "az" },
    { "name": "Bambara", "code": "bm" },
    { "name": "Basque", "code": "eu" },
    { "name": "Belarusian", "code": "be" },
    { "name": "Bengali", "code": "bn" },
    { "name": "Bhojpuri", "code": "bho" },
    { "name": "Bosnian", "code": "bs" },
    { "name": "Bulgarian", "code": "bg" },
    { "name": "Catalan", "code": "ca" },
    { "name": "Cebuano", "code": "ceb" },
    { "name": "Chichewa", "code": "ny" },
    { "name": "Chinese (Simplified)", "code": "zh-CN" },
    { "name": "Chinese (Traditional)", "code": "zh-TW" },
    { "name": "Corsican", "code": "co" },
    { "name": "Croatian", "code": "hr" },
    { "name": "Czech", "code": "cs" },
    { "name": "Danish", "code": "da" },
    { "name": "Dhivehi", "code": "dv" },
    { "name": "Dogri", "code": "doi" },
    { "name": "Dutch", "code": "nl" },
    { "name": "English", "code": "en" },
    { "name": "Esperanto", "code": "eo" },
    { "name": "Estonian", "code": "et" },
    { "name": "Ewe", "code": "ee" },
    { "name": "Filipino", "code": "fil" },
    { "name": "Finnish", "code": "fi" },
    { "name": "French", "code": "fr" },
    { "name": "Frisian", "code": "fy" },
    { "name": "Galician", "code": "gl" },
    { "name": "Georgian", "code": "ka" },
    { "name": "German", "code": "de" },
    { "name": "Greek", "code": "el" },
    { "name": "Guarani", "code": "gn" },
    { "name": "Gujarati", "code": "gu" },
    { "name": "Haitian Creole", "code": "ht" },
    { "name": "Hausa", "code": "ha" },
    { "name": "Hawaiian", "code": "haw" },
    { "name": "Hebrew", "code": "iw" },
    { "name": "Hindi", "code": "hi" },
    { "name": "Hmong", "code": "hmn" },
    { "name": "Hungarian", "code": "hu" },
    { "name": "Icelandic", "code": "is" },
    { "name": "Igbo", "code": "ig" },
    { "name": "Ilocano", "code": "ilo" },
    { "name": "Indonesian", "code": "id" },
    { "name": "Irish", "code": "ga" },
    { "name": "Italian", "code": "it" },
    { "name": "Japanese", "code": "ja" },
    { "name": "Javanese", "code": "jw" },
    { "name": "Kannada", "code": "kn" },
    { "name": "Kazakh", "code": "kk" },
    { "name": "Khmer", "code": "km" },
    { "name": "Kinyarwanda", "code": "rw" },
    { "name": "Konkani", "code": "kok" },
    { "name": "Korean", "code": "ko" },
    { "name": "Krio", "code": "kri" },
    { "name": "Kurdish (Kurmanji)", "code": "ku" },
    { "name": "Kurdish (Sorani)", "code": "ckb" },
    { "name": "Kyrgyz", "code": "ky" },
    { "name": "Lao", "code": "lo" },
    { "name": "Latin", "code": "la" },
    { "name": "Latvian", "code": "lv" },
    { "name": "Lingala", "code": "ln" },
    { "name": "Lithuanian", "code": "lt" },
    { "name": "Luganda", "code": "lg" },
    { "name": "Luxembourgish", "code": "lb" },
    { "name": "Macedonian", "code": "mk" },
    { "name": "Maithili", "code": "mai" },
    { "name": "Malagasy", "code": "mg" },
    { "name": "Malay", "code": "ms" },
    { "name": "Malayalam", "code": "ml" },
    { "name": "Maltese", "code": "mt" },
    { "name": "Maori", "code": "mi" },
    { "name": "Marathi", "code": "mr" },
    { "name": "Meiteilon (Manipuri)", "code": "mni-Mtei" },
    { "name": "Mizo", "code": "lus" },
    { "name": "Mongolian", "code": "mn" },
    { "name": "Myanmar (Burmese)", "code": "my" },
    { "name": "Nepali", "code": "ne" },
    { "name": "Norwegian", "code": "no" },
    { "name": "Odia (Oriya)", "code": "or" },
    { "name": "Oromo", "code": "om" },
    { "name": "Pashto", "code": "ps" },
    { "name": "Persian", "code": "fa" },
    { "name": "Polish", "code": "pl" },
    { "name": "Portuguese", "code": "pt" },
    { "name": "Punjabi", "code": "pa" },
    { "name": "Quechua", "code": "qu" },
    { "name": "Romanian", "code": "ro" },
    { "name": "Russian", "code": "ru" },
    { "name": "Samoan", "code": "sm" },
    { "name": "Sanskrit", "code": "sa" },
    { "name": "Scots Gaelic", "code": "gd" },
    { "name": "Sepedi", "code": "nso" },
    { "name": "Serbian", "code": "sr" },
    { "name": "Sesotho", "code": "st" },
    { "name": "Shona", "code": "sn" },
    { "name": "Sindhi", "code": "sd" },
    { "name": "Sinhala", "code": "si" },
    { "name": "Slovak", "code": "sk" },
    { "name": "Slovenian", "code": "sl" },
    { "name": "Somali", "code": "so" },
    { "name": "Spanish", "code": "es" },
    { "name": "Sundanese", "code": "su" },
    { "name": "Swahili", "code": "sw" },
    { "name": "Swedish", "code": "sv" },
    { "name": "Tajik", "code": "tg" },
    { "name": "Tamil", "code": "ta" },
    { "name": "Tatar", "code": "tt" },
    { "name": "Telugu", "code": "te" },
    { "name": "Thai", "code": "th" },
    { "name": "Tigrinya", "code": "ti" },
    { "name": "Tsonga", "code": "ts" },
    { "name": "Turkish", "code": "tr" },
    { "name": "Turkmen", "code": "tk" },
    { "name": "Twi", "code": "tw" },
    { "name": "Ukrainian", "code": "uk" },
    { "name": "Urdu", "code": "ur" },
    { "name": "Uzbek", "code": "uz" },
    { "name": "Vietnamese", "code": "vi" },
    { "name": "Welsh", "code": "cy" },
    { "name": "Xhosa", "code": "xh" },
    { "name": "Yiddish", "code": "yi" },
    { "name": "Yoruba", "code": "yo" },
    { "name": "Zulu", "code": "zu" },
    { "name": "Abkhazian", "code": "ab" },
    { "name": "Akan", "code": "ak" },
    { "name": "Aragonese", "code": "an" },
    { "name": "Avaric", "code": "av" },
    { "name": "Avestan", "code": "ae" },
    { "name": "Balochi", "code": "bal" },
    { "name": "Basa", "code": "bas" },
    { "name": "Bashkir", "code": "ba" },
    { "name": "Bislama", "code": "bi" },
    { "name": "Breton", "code": "br" },
    { "name": "Buriat", "code": "bua" },
    { "name": "Cantonese", "code": "yue" },
    { "name": "Chamorro", "code": "ch" },
    { "name": "Chechen", "code": "ce" },
    { "name": "Chuvash", "code": "cv" },
    { "name": "Cornish", "code": "kw" },
    { "name": "Erzya", "code": "myv" },
    { "name": "Faroese", "code": "fo" },
    { "name": "Fijian", "code": "fj" },
    { "name": "Fon", "code": "fon" },
    { "name": "Fulah", "code": "ff" },
    { "name": "Gaelic (Manx)", "code": "gv" },
    { "name": "Ganda", "code": "lg" },
    { "name": "Hakka", "code": "hak" },
    { "name": "Herero", "code": "hz" },
    { "name": "Hiri Motu", "code": "ho" },
    { "name": "Iban", "code": "iba" },
    { "name": "Ido", "code": "io" },
    { "name": "Inuktitut", "code": "iu" },
    { "name": "Inupiaq", "code": "ik" },
    { "name": "Interlingua", "code": "ia" },
    { "name": "Interlingue", "code": "ie" },
    { "name": "Kanuri", "code": "kr" },
    { "name": "Kashmiri", "code": "ks" },
    { "name": "Kikongo", "code": "kg" },
    { "name": "Komi", "code": "kv" },
    { "name": "Kongo", "code": "kg" },
    { "name": "Kuanyama", "code": "kj" },
    { "name": "Limburgan", "code": "li" },
    { "name": "Luba-Katanga", "code": "lu" },
    { "name": "Luo", "code": "luo" },
    { "name": "Luyia", "code": "luy" },
    { "name": "Mari", "code": "chm" },
    { "name": "Marshallese", "code": "mh" },
    { "name": "Nauru", "code": "na" },
    { "name": "Navajo", "code": "nv" },
    { "name": "Ndonga", "code": "ng" },
    { "name": "North Ndebele", "code": "nd" },
    { "name": "Northern Sami", "code": "se" },
    { "name": "Occitan", "code": "oc" },
    { "name": "Ojibwa", "code": "oj" },
    { "name": "Ossetic", "code": "os" },
    { "name": "Pali", "code": "pi" },
    { "name": "Papiamento", "code": "pap" },
    { "name": "Punjabi (Shahmukhi)", "code": "pa-Arab" },
    { "name": "Qʼeqchiʼ", "code": "kek" },
    { "name": "Rundi", "code": "rn" },
    { "name": "Sango", "code": "sg" },
    { "name": "Sardinian", "code": "sc" },
    { "name": "Sicilian", "code": "scn" },
    { "name": "South Ndebele", "code": "nr" },
    { "name": "Swati", "code": "ss" },
    { "name": "Tahitian", "code": "ty" },
    { "name": "Tamazight (Amazigh)", "code": "ber" },
    { "name": "Tok Pisin", "code": "tpi" },
    { "name": "Tonga", "code": "to" },
    { "name": "Tswana", "code": "tn" },
    { "name": "Udmurt", "code": "udm" },
    { "name": "Venda", "code": "ve" },
    { "name": "Volapük", "code": "vo" },
    { "name": "Walloon", "code": "wa" },
    { "name": "Wolof", "code": "wo" },
    { "name": "Zhuang", "code": "za" },
    { "name": "Azerbaijani (Cyrillic)", "code": "az-Cyrl" },
    { "name": "Bambara (N’ko)", "code": "bm-Nkoo" },
    { "name": "Bislama (Latin)", "code": "bi-Latn" },
    { "name": "Bokmål", "code": "nb" },
    { "name": "Chhattisgarhi", "code": "hne" },
    { "name": "Dinka", "code": "din" },
    { "name": "Dzongkha", "code": "dz" },
    { "name": "Fanti", "code": "fat" },
    { "name": "Ga", "code": "gaa" },
    { "name": "Greenlandic", "code": "kl" },
    { "name": "Haryanvi", "code": "bgc" },
    { "name": "Ingush", "code": "inh" },
    { "name": "Karachay-Balkar", "code": "krc" },
    { "name": "Kashubian", "code": "csb" },
    { "name": "Khasi", "code": "kha" },
    { "name": "Lak", "code": "lbe" },
    { "name": "Lezghian", "code": "lez" },
    { "name": "Ligurian", "code": "lij" },
    { "name": "Magahi", "code": "mag" },
    { "name": "Moksha", "code": "mdf" },
    { "name": "N’ko", "code": "nqo" },
    { "name": "Ossetic (Cyrillic)", "code": "os-Cyrl" },
    { "name": "Pangasinan", "code": "pag" },
    { "name": "Pushto (Pashto)", "code": "ps" },
    { "name": "Santhali", "code": "sat" },
    { "name": "Shona (Latin)", "code": "sn-Latn" },
    { "name": "Somali (Arabic)", "code": "so-Arab" },
    { "name": "Tibetan", "code": "bo" },
    { "name": "Tswana (Latin)", "code": "tn-Latn" },
    { "name": "Tulu", "code": "tcy" },
    { "name": "Twi (Akan)", "code": "tw" },
    { "name": "Upper Sorbian", "code": "hsb" },
    { "name": "Uyghur", "code": "ug" },
    { "name": "Yakut", "code": "sah" },
    { "name": "Zomi", "code": "zom" }
];